[language.haskell]
filetypes = ["haskell"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "haskell-language-server-wrapper"
args = ["--lsp"]

[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "gopls"
args = ["serve"]

[language.python]
filetypes = ["python"]
roots = [".git", ".hg"]
command = "pylsp"
args = []

[language.typescript]
filetypes = ["typescript"]
roots = ["package.json", ".git"]
command = "typescript-language-server"
args = ["--stdio"]
