[colors.primary]
background = "0x2C2C2C"
foreground = "0xDCDCCC"

[colors.normal]
black = "0x3F3F3F"
red = "0x705050"
green = "0x60B48A"
yellow = "0xDFAF8F"
blue = "0x9AB8D7"
magenta = "0xDC8CC3"
cyan = "0x8CD0D3"
white = "0xDCDCCC"

[colors.bright]
black = "0x709080"
red = "0xDCA3A3"
green = "0x72D5A3"
yellow = "0xF0DFAF"
blue = "0x94BFF3"
magenta = "0xEC93D3"
cyan = "0x93E0E3"
white = "0xFFFFFF"

[colors.cobalt2]
primary = "{'background': '0x122637', 'foreground': '0xffffff'}"
cursor = "{'text': '0x122637', 'cursor': '0xf0cb09'}"
normal = "{'black': '0x000000', 'red': '0xff0000', 'green': '0x37dd21', 'yellow': '0xfee409', 'blue': '0x1460d2', 'magenta': '0xff005d', 'cyan': '0x00bbbb', 'white': '0xbbbbbb'}"
bright = "{'black': '0x545454', 'red': '0xf40d17', 'green': '0x3bcf1d', 'yellow': '0xecc809', 'blue': '0x5555ff', 'magenta': '0xff55ff', 'cyan': '0x6ae3f9', 'white': '0xffffff'}"

